# Generated by Django 2.2.13 on 2020-06-25 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsource', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
        migrations.RemoveField(
            model_name='qbank',
            name='question',
        ),
        migrations.AddField(
            model_name='qbank',
            name='question',
            field=models.ManyToManyField(to='qsource.Question'),
        ),
    ]
