# Generated by Django 2.2.13 on 2020-06-25 09:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsource', '0002_auto_20200625_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='qbank',
            name='headline',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='qbank',
            name='option1',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='qbank',
            name='option2',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='qbank',
            name='option3',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='qbank',
            name='option4',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
