# Generated by Django 2.2.13 on 2020-06-26 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qsource', '0003_auto_20200625_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qbank',
            name='headline',
            field=models.CharField(blank=True, max_length=400),
        ),
    ]
